[package]
name = "tufaceous-brand-metadata"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true

[lints]
workspace = true
