[package]
name = "tufaceous"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[test]]
name = "manifest-tests"
harness = false

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
buf-list.workspace = true
bytes.workspace = true
camino.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
flate2.workspace = true
futures.workspace = true
hubtools.workspace = true
humantime.workspace = true
semver.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-term.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tough.workspace = true
tufaceous-artifact.workspace = true
tufaceous-lib.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
datatest-stable.workspace = true
dropshot.workspace = true
fs-err.workspace = true
predicates.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
