# This manifest has two measurement corpora that hash to the same contents. This
# is not allowed.

system_version = "1.0.0"

[[artifact.control_plane]]
name = "fake-control-plane"
version = "1.0.0"
[artifact.control_plane.source]
kind = "composite-control-plane"
zones = [
    { kind = "fake", artifact_name = "zone-1", file_name = "zone1.tar.gz", size = "1MiB" },
    { kind = "fake", artifact_name = "zone-2", file_name = "zone2.tar.gz", size = "1MiB" },
]
measurement_corpus = [
    { kind = "fake", artifact_name = "measurement1", file_name = "measurement1.cbor", size = "1MiB" },
    { kind = "fake", artifact_name = "measurement1", file_name = "measurement1-dup.cbor", size = "1MiB" },
]
