# This manifest has two control plane zones that hash to the same contents. This
# is not allowed.

system_version = "1.0.0"

[[artifact.control_plane]]
name = "fake-control-plane"
version = "1.0.0"
[artifact.control_plane.source]
kind = "composite-control-plane"
zones = [
    { kind = "fake_zone", artifact_name = "zone-1", file_name = "zone1.tar.gz", size = "1MiB" },
    { kind = "fake_zone", artifact_name = "zone-1", file_name = "zone1-dup.tar.gz", size = "1MiB" },
]
measurement_corpus = [
    { kind = "fake_measurement", artifact_name = "measurement1", file_name = "measurement1.cbor", size = "1MiB" },
    { kind = "fake_measurement", artifact_name = "measurement2", file_name = "measurement2.cbor", size = "1MiB" },
]
