// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

use std::collections::BTreeMap;
use std::fmt::Debug;
use std::fmt::Display;
use std::str::FromStr;

use byte_wrapper::HexArray;
use byte_wrapper::ParseHexError;
use daft::Diffable;
use serde::Deserialize;
use serde::Serialize;

use crate::ArtifactVersion;
use crate::DisplayTags;
use crate::KnownArtifactTags;

/// An artifact in a repository.
///
/// Artifacts are files present in a repository (in TUF parlance, "targets")
/// that the control plane must be aware of and that are used during
/// control-plane-driven update of the system.
#[derive(
    Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize,
)]
pub struct Artifact {
    /// The version of the artifact.
    pub version: ArtifactVersion,

    /// The artifact's tags.
    ///
    /// Tags describe how an artifact is to be used by the control plane.
    /// In this form, they are an arbitrary mapping of string keys to string
    /// values. Using [`Artifact::known_tags`], they can be (fallibly) converted
    /// into a strongly-typed description of the artifact.
    ///
    /// When recording artifacts for later use, the control plane must always
    /// record these tags as-is, even if `Artifact::known_tags` returns `None`.
    pub tags: BTreeMap<String, String>,

    /// The SHA256 checksum of the artifact.
    pub hash: ArtifactHash,

    /// The length of the artifact in bytes.
    pub length: u64,
}

impl Artifact {
    /// Resolves [`Artifact::tags`] into [`KnownArtifactTags`].
    ///
    /// Returns `None` if the tags do not resolve to any known artifact. This
    /// is expected if the repository was generated by a future version of
    /// Tufaceous that knows about some new artifact.
    ///
    /// If you instead want an error when the tags do not resolve to any known
    /// artifact, use [`KnownArtifactTags::from_tags`].
    pub fn known_tags(&self) -> Option<KnownArtifactTags> {
        KnownArtifactTags::from_tags(self.tags.clone()).ok()
    }

    /// Returns an adapter for displaying [`Artifact::tags`] as a human-readable
    /// string.
    pub fn display_tags(&self) -> DisplayTags<'_> {
        DisplayTags::from(&self.tags)
    }
}

/// The SHA256 checksum of an artifact.
#[derive(
    Copy,
    Clone,
    Diffable,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
#[daft(leaf)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "proptest", derive(test_strategy::Arbitrary))]
#[serde(transparent)]
pub struct ArtifactHash(
    #[serde(with = "HexArray::<32>")]
    #[cfg_attr(
        feature = "schemars",
        schemars(schema_with = "HexArray::<32>::json_schema")
    )]
    pub [u8; 32],
);

impl AsRef<[u8]> for ArtifactHash {
    fn as_ref(&self) -> &[u8] {
        self.0.as_slice()
    }
}

impl Debug for ArtifactHash {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("ArtifactHash").field(&HexArray(self.0)).finish()
    }
}

impl Display for ArtifactHash {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Display::fmt(&HexArray(self.0), f)
    }
}

impl FromStr for ArtifactHash {
    type Err = ParseHexError;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        s.parse()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn display_respects_padding() {
        let h = ArtifactHash([0; 32]);
        assert_eq!(
            format!("{h:x>100}"),
            "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx0000000000000000000000000000000000000000000000000000000000000000"
        );
    }
}
